[FIX] account_asset_invoice_line_link: vals dict is used in Form
Form requires many2one entries be model records instead of their ids. Without this fix, when validating an invoice with assets, you get "AttributeError: 'int' object has no attribute 'id'".